vault-mutating-webhook: allow specifying pod securityContext and full container securityContext
banzaicloud/bank-vaults pull request #1119
Opened 2020-09-24 20:43 UTC by dbeal-wiser

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | none
| License         | Apache 2.0

### What's in this PR?

It is not possible to specify full gamut of `pod.spec.container[].securityContext` or `pod.spec.securityContext` without modifying the chart itself. In our case, we needed to set `pod.spec.securityContext.fsGroup` to the same group as the user in order to be compatible with AWS [OIDC EKS IAM](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html). This PR includes a minor fix to allow specifying all `securityContext` options on the webhook deployment. There should be no effective change unless custom options are set.

### Additional context

Users who may have set custom options and not realized they were unset may be affected. We tested the implementation on our in-house setup and verified options can be set appropriately.

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [ ] (not needed) User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

2020-09-24 20:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/banzaicloud/bank-vaults?pullRequest=1119) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/banzaicloud/bank-vaults?pullRequest=1119) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/banzaicloud/bank-vaults?pullRequest=1119) it.</sub>

2020-09-25 05:12 UTC, bonifaido commented on charts/vault-secrets-webhook/templates/webhook-deployment.yaml
> +  {{- if .Values.podSecurityContext }}
`podSecurityContext` should be mentioned in the values.yaml file with a default empty value. Also in the README.

2020-09-25 05:12 UTC, bonifaido requested changes
Please bump the chart version as well.

2020-09-25 18:03 UTC, dbeal-wiser commented
btw im not sure about if I should update the spacing for the README.md table, let me know if that should be adjusted or if the default value is just so long that its not worth it.

2020-09-26 07:12 UTC, bonifaido approved these changes
It is absolutely fine @dbeal-wiser, thanks!

2020-09-26 07:13 UTC, merged