[webhook] Kill container process when non-renewable lease expired.
banzaicloud/bank-vaults pull request #1239
Opened 2021-01-20 14:16 UTC by moskitone

Signed-off-by: Volodymyr Moseichuk <moskitone@gmail.com>

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | Messages in slack
| License         | Apache 2.0

### What's in this PR?
[webhook] vault.security.banzaicloud.io/vault-env-daemon-exit-when-expired - New annotation for terminating pods with expired non-renewable secrets in vault-env daemon mode.
[chart-webhook] - extend RBAC with ability to get serviceaccounts (required by new go-containerregistry).

### Why?
Due to limitations in vault 
https://github.com/hashicorp/vault/blob/master/builtin/logical/aws/secret_access_keys.go#L200-L201
and https://github.com/banzaicloud/bank-vaults/blob/master/internal/injector/injector.go#L254 
this part https://github.com/banzaicloud/bank-vaults/blob/master/cmd/vault-env/main.go#L104-L111 newer starts. After lease expiration container remains in RUNNING state with expired credentials.

### Additional context
Tested only with aws sts credentials.

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

2021-01-21 09:47 UTC, bonifaido commented
- I think this should be the default behavior, so I wouldn't introduce a new annotation for this, what do you think @moskitone?
- Could you please bump the chart version?

2021-01-21 09:48 UTC, bonifaido requested changes
See my comments above.

2021-01-21 10:38 UTC, moskitone commented
> * I think this should be the default behavior, so I wouldn't introduce a new annotation for this, what do you think @moskitone?

Just wanted to be on the safe side and didn't want to break default behaviour.

> * Could you please bump the chart version?

Sure

2021-01-25 14:58 UTC, moskitone commented
Hi @bonifaido 
Could you please check it?

2021-01-26 07:37 UTC, bonifaido approved these changes
LGTM! Thanks @moskitone nice fix!

2021-01-26 07:38 UTC, merged