Adding support for topologySpreadConstraints
banzaicloud/bank-vaults pull request #1359
Opened 2021-06-16 15:42 UTC by johnwoo247

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | Yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | 1356
| License         | Apache 2.0

### What's in this PR?

Adds a new configuration parameter "topologySpreadConstraint" to the webhook deployment template and the values.yaml.  README updated with  this new parameter

2021-06-16 15:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/banzaicloud/bank-vaults?pullRequest=1359) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/banzaicloud/bank-vaults?pullRequest=1359) before we can accept your contribution.<br/><hr/>**John Woo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/banzaicloud/bank-vaults?pullRequest=1359) it.</sub>

2021-06-17 08:05 UTC, bonifaido requested changes
Please bump the chart version as well.

2021-06-17 08:40 UTC, pbalogh-sa reviewed
please bumb chart version, otherwise LGTM

2021-06-18 07:35 UTC, bonifaido approved these changes

2021-06-18 07:36 UTC, merged