feature: add extra containers sections
banzaicloud/bank-vaults pull request #1505
Opened 2021-12-30 12:57 UTC by Moon1706

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | no
| License         | Apache 2.0

### What's in this PR?

This merge request adds extra init and sidecar containers in bank-vault pod. It may be useful when you sidecar containers e.g. consul-agent. Also, that helps DevOps engineers customize bank-vault. These sections are used in the official Vault chart https://github.com/hashicorp/vault-helm.

### Additional context

This MR tested with `helm template .`

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [ ] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

2021-12-30 12:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/banzaicloud/bank-vaults?pullRequest=1505) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/banzaicloud/bank-vaults?pullRequest=1505) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/banzaicloud/bank-vaults?pullRequest=1505) it.</sub>

2022-01-05 08:50 UTC, pbalogh-sa requested changes

2022-01-05 08:50 UTC, pbalogh-sa commented on charts/vault/README.md
> +| `extraInitContainers`                | Init containers to add to the bank-vault pod              | `[]`                                                                                            |
pleas fix bank-vault to bank-vaults

2022-01-05 08:50 UTC, pbalogh-sa commented on charts/vault/README.md
> +| `extraContainers`                    | Sidecar containers to add to the bank-vaul pod            | `[]`                                                                                            |
pleas fix bank-vaul to bank-vaults

2022-01-10 05:19 UTC, Moon1706 commented on charts/vault/README.md
> +| `extraInitContainers`                | Init containers to add to the bank-vault pod              | `[]`                                                                                            |
Done

2022-01-10 05:19 UTC, Moon1706 commented on charts/vault/README.md
> +| `extraContainers`                    | Sidecar containers to add to the bank-vaul pod            | `[]`                                                                                            |
Done

2022-01-10 09:57 UTC, pbalogh-sa approved these changes

2022-01-10 10:18 UTC, merged