Remove vault-env (and some operator leftovers)
banzaicloud/bank-vaults pull request #1941
Opened 2023-06-08 15:43 UTC by akijakya

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no]
| API breaks?     | no
| Deprecations?   | yes
| Related tickets | -
| License         | Apache 2.0

### What's in this PR?

- removed some more operator-related stuff
- removed vault-env, set the location of the new image in webhook chart

### Why?

Both of these got their own repos under the [bank-vaults org](https://github.com/bank-vaults)

### Checklist

- [X] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- ~User guide and development docs updated (if needed)~
- [X] Related Helm chart(s) updated (if needed)

2023-06-08 22:15 UTC, sagikazarmark requested changes
Let's keep internal in this repo for now. We can figure out what to do with the duplicate code later.

2023-06-09 08:36 UTC, sagikazarmark commented on charts/vault-secrets-webhook/values.yaml
> +  repository: ghcr.io/bank-vaults/vault-env
This is already done: https://github.com/banzaicloud/bank-vaults/blob/main/charts/vault-secrets-webhook/values.yaml#L51

2023-06-09 08:39 UTC, akijakya commented on charts/vault-secrets-webhook/values.yaml
> +  repository: ghcr.io/bank-vaults/vault-env
ok

2023-06-09 09:02 UTC, sagikazarmark approved these changes

2023-06-09 09:02 UTC, merged