feat: Add configurable AWS KMS encryption context
banzaicloud/bank-vaults pull request #1968
Opened 2023-06-21 14:24 UTC by kirilvasilev

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?
This PR introduced a new feature allowing you to configure the AWS KMS encryption context

### Why?
In some cases, existing recovery/unseal keys may have been encrypted with a different encryption context

### Additional context
In our use case, we have an existing vault cluster that has existing unseal keys that are encrypted with a custom encryption context. This feature will allow us to migrate this vault cluster to be managed by bank-vaults.

### Checklist
- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

2023-06-21 16:40 UTC, ats0stv commented
Thanks for this MR. This will be useful for the wider community as well IMO.

2023-06-28 08:42 UTC, sagikazarmark requested changes
@kirilvasilev Thank you for your PR!

I had a few questions and suggestions. Can you please take a look at them?

2023-06-28 08:42 UTC, sagikazarmark commented on cmd/bank-vaults/main.go
> +	configStringVar(rootCmd, cfgAWSKMSEncryptionContext, "Tool=bank-vaults", "The encryption context that AWS KMS will use to encrypt values")
I'm not entirely convinced it's a good idea to have a default. What purpose does it serve? I think we should let users leave this empty.

2023-06-28 08:42 UTC, sagikazarmark commented on pkg/kv/awskms/awskms.go
> +
I assume leftover from testing, please remove.

2023-06-28 08:42 UTC, sagikazarmark commented on pkg/kv/awskms/awskms.go
> +	}
Shouldn't we allow more than one key-value pairs?

https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#encrypt_context

2023-06-28 08:42 UTC, sagikazarmark commented on pkg/kv/awskms/awskms.go
> +		},
You could use `aws.StringMap` instead, once multiple encryption contexts are implemented.

2023-06-28 08:42 UTC, sagikazarmark commented on cmd/bank-vaults/main.go
> +	configStringVar(rootCmd, cfgAWSKMSEncryptionContext, "Tool=bank-vaults", "The encryption context that AWS KMS will use to encrypt values")
Also, I guess we should be accepting more than one. And since the end result is a map, `StringToStringVar` may be a better choice (or `configStringMapVar` as it's called here).

2023-06-28 11:03 UTC, kirilvasilev commented on cmd/bank-vaults/main.go
> +	configStringVar(rootCmd, cfgAWSKMSEncryptionContext, "Tool=bank-vaults", "The encryption context that AWS KMS will use to encrypt values")
Excellent suggestions!
My only incentive to keep the default encryption context is for backward compatibility.
Things already encrypted with that context won't be decryptable without it.

2023-06-28 14:38 UTC, sagikazarmark commented on cmd/bank-vaults/main.go
> +	configStringVar(rootCmd, cfgAWSKMSEncryptionContext, "Tool=bank-vaults", "The encryption context that AWS KMS will use to encrypt values")
Agreed! I missed that there was a default encryption context default, but it makes sense.

2023-06-28 14:47 UTC, sagikazarmark approved these changes

2023-06-28 14:47 UTC, merged

2023-06-28 14:48 UTC, sagikazarmark commented
Thank you @kirilvasilev!

We will release a new version in two weeks. Until then, I'm going to tag a new dev version.